### PR TITLE
test(sauce): Add IE11 SauceLabs image comparison tests

### PR DESCRIPTION
**Pull request by obartra**
🎉 Add support for IE 11 and fix bugs to add compatibility 🎉 

WIP: Behavior as expected, SauceLabs different browser windows strike again

| IE11 | Chrome | Diff |
|-----|---------|-----|
|  |  |  |

### CODE REVIEW

**Comment by arahansen** [comment]
I noticed that we were targeting grandchildren for the max-width of non-layout elements. this was messing with the percentage-based max widths on ie11. 

Also, it seems `.wrapper` doesn't exist anymore, so pulled that out too.

If we have a good reason to be targeting grandchildren, feel free to back out my commit. But I didn't immediately see any breaking changes from removing that selector.

**Comment by obartra** [comment]
ah yes I missed that, it's still a WIP, I need to update the images on the PR. The stretch problem is fixed. Current issues are incorrect width calculation and layout type parent height set at 100%.

The layout one doesn't have impact on the children and may be the only way to get cross browser consistent behavior with stretch.

The width issue is the blocking one since things overflow differently on IE11 with current changes

I think we're getting pretty close

**Comment by arahansen** [comment]
I'm not convinced my change will work across the board. But it seemed to do the trick on the search page example.

Without the fix:
capture


With the fix:
capture

notice, for example, how "First View | Second View" is collapsed practically off the screen without the fix, but the width is set correctly with the fix in place

**Comment by obartra** [comment]
That's fine, I'm still trying to figure out the SauceLabs issues, I would say let's split the work into 2 branches, that way we can both keep looking into it

**Comment by obartra** [comment]
There are some cross browser issues with "Search" and "Two Sections" examples. They are related to the IE11 workaround for min-height.

SauceLabs window size issues are resolved, onward!

**Comment by arahansen** [comment]
Looks like the issue is the footer showing up when the content should be pushing below the fold?

**Comment by obartra** [comment]
yup. The trick is in solving this without hacks or extra dom markup in a way that works cross browser. Now it works on IE11 but the fix for Safari breaks it for chrome and vice versa. Open to suggestions

**Comment by obartra** [comment]
Closing in favor of https://github.com/obartra/reflex/pull/227

**Pull request closed without merging**
